### PR TITLE
Updates to BooksView + homepage

### PR DESCRIPTION
**Pull request by QuickWick123**

### CODE REVIEW

**Review by houyhourung — COMMENTED** [review]
Question about boostore/settings.py , I see that you install 'rest_framework' into the INSTALLED_APP. Does the app require a pip install? If so, please list it in the requirement.txt file

**Review by houyhourung — COMMENTED** [review]
I tested the new models.py and restored it to the new database, my feature is working fine and it seems like the shopping cart feature is also working!

**Comment by QuickWick123** [comment]
Hello houy, there was a question about 'rest_framework' variable within the INSTALLED_APP. There is nothing to do. This is a key variable that was missing which did not let us access 127.0.0.1:8000/book/ or 127.0.0.1:8000/detail/1/ There is nothing else to do. The requirements have been fulfilled via the install djangorestframework (or perhaps it was install djangoframework) command and is already included in the requirements.txt . With this variable added, we now have full access.

**Review by houyhourung — APPROVED** [review]
Good to go then!

**Review by QuickWick123 — COMMENTED** [review]
hopefully this works

**Pull request merged**
